### ISSUE TITLE
КР 2016 задача 5 пункт г

### ISSUE THREAD

**Issue by NikolayGolikov** [bdemeshev/metrics_hse_exams#10]
Вероятность должна считаться, как e^u/(1+e^u), а в решении 1/(1+e^u)

**Comment by bdemeshev** [comment]
Лучше указывать кр конкретнее :) Проверил. Ошибку не нашел, там написано 1/(1 + exp(-0.7+1.5)), то есть написано 1/(1+e^{-u}).
