### ISSUE TITLE
Неправильное вычисление ДИ в задаче №4(г) раздела "10.4. Контрольная работа-1. Базовая часть"

### ISSUE THREAD

**Issue by ivanskv2000** [bdemeshev/metrics_hse_exams#14]
**Вместо дисперсии y_hat нужно брать дисперсию y-y_hat!**

![IMAGE 2020-10-21 21:52:53](https://user-images.githubusercontent.com/54892573/96769402-c5b0bf00-13e7-11eb-9400-7ccc30663635.jpg)
![IMAGE 2020-10-21 21:52:55](https://user-images.githubusercontent.com/54892573/96769404-c6e1ec00-13e7-11eb-99f6-4688de56e556.jpg)

**Comment by bdemeshev** [comment]
Ага, спасибо, поправил!
