### ISSUE TITLE
Микро-опечатка в решениях кр2, задача 3, 2018-2019

### ISSUE THREAD

**Issue by rk-helper** [bdemeshev/metrics_hse_exams#15]
Так как, для того, чтобы посчитать F_crit надо сделать F.ppf(1-alpha, K_ur-K_r; N - K_ur).
Так как количество параметров в UR модели 6, а общее число наблюдение 500, тогда вторая степень свободы будет 494, а в решении 496.
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/62377740/101069270-d047a200-35aa-11eb-9248-f60136e06add.png">

**Comment by bdemeshev** [comment]
ага, супер, спасибо!
